# --- Kafka reactive messaging channels ---
mp.messaging.incoming.validation-requests.connector=smallrye-kafka
mp.messaging.incoming.validation-requests.topic=text-validation-request
mp.messaging.incoming.validation-requests.auto.offset.reset=earliest

mp.messaging.outgoing.validation-responses.connector=smallrye-kafka
mp.messaging.outgoing.validation-responses.topic=text-validation-response

quarkus.http.port=8081

quarkus.micrometer.export.prometheus.enabled=true
# sinnvolle automatische Binder
quarkus.micrometer.export.prometheus.enabled=true
quarkus.micrometer.binder.jvm=true
quarkus.micrometer.binder.system=true
quarkus.micrometer.binder.http-server.enabled=true
quarkus.micrometer.binder.messaging.enabled=true
quarkus.micrometer.binder.kafka.enabled=true

quarkus.kafka.health.enabled=true