# --- Kafka reactive messaging channels ---
mp.messaging.outgoing.validation-requests.connector=smallrye-kafka
mp.messaging.outgoing.validation-requests.topic=text-validation-request

mp.messaging.incoming.validation-responses.connector=smallrye-kafka
mp.messaging.incoming.validation-responses.topic=text-validation-response
mp.messaging.incoming.validation-responses.auto.offset.reset=earliest

# ensure string payloads for kafka
mp.messaging.outgoing.validation-requests.value.serializer=org.apache.kafka.common.serialization.StringSerializer
mp.messaging.incoming.validation-responses.value.deserializer=org.apache.kafka.common.serialization.StringDeserializer

quarkus.http.port=8080

quarkus.datasource.db-kind=postgresql
quarkus.hibernate-orm.database.generation=update

quarkus.micrometer.export.prometheus.enabled=true
# sinnvolle automatische Binder
quarkus.micrometer.binder.jvm=true
quarkus.micrometer.binder.system=true
quarkus.micrometer.binder.http-server.enabled=true

quarkus.kafka.health.enabled=true
quarkus.datasource.health.enabled=true